#!/bin/bash

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-rancher}

if $(echo ${TAG} | grep -q dirty); then
    TAG=dev
fi

cp ../bin/rancher-metadata .
docker build -t ${REPO}/metadata:${TAG} .

echo Built ${REPO}/metadata:${TAG}

cd ..

CONTENT=$(</proc/sys/kernel/random/uuid)

rm -rf dist/artifacts

mkdir -p build/${CONTENT}
mkdir -p dist/artifacts

cp -rf apply.sh bin content build/${CONTENT}

cd build

sha1sum -b $(find ${CONTENT} -type f) > ${CONTENT}/SHA1SUMS
sha1sum ${CONTENT}/SHA1SUMS > ${CONTENT}/SHA1SUMSSUM

tar czf ../dist/artifacts/rancher-metadata.tar.gz ${CONTENT}
echo Created dist/artifacts/rancher-metadata.tar.gz
